---
- name: 'Configure and start Jira'
  become: true
  block:
    - name: 'Create Jira unit for SystemD'
      ansible.builtin.template:
        src: 'jira.service.j2'
        dest: '/etc/systemd/system/jira.service'
        owner: '{{ jira_username }}'
        group: '{{ jira_group }}'
        mode: 0644
      notify: Restart Jira

    - name: 'Configure Jira server'
      ansible.builtin.template:
        src: 'server.xml.j2'
        dest: '{{ _jira_application_path }}/conf/server.xml'
        owner: '{{ jira_username }}'
        group: '{{ jira_group }}'
        mode: 0644
      notify: Restart Jira

    - name: 'Configure Jira environment'
      ansible.builtin.template:
        src: 'setenv.sh.j2'
        dest: '{{ _jira_application_path }}/bin/setenv.sh'
        owner: '{{ jira_username }}'
        group: '{{ jira_group }}'
        mode: 0755
      notify: Restart Jira

    - name: 'Configure Jira database connection'
      ansible.builtin.template:
        src: 'dbconfig.xml.j2'
        dest: '{{ jira_home_path }}/dbconfig.xml'
        owner: '{{ jira_username }}'
        group: '{{ jira_group }}'
        mode: 0600
      notify: Restart Jira
      when: jira_db_configuration | bool

    - name: 'Ensure Jira is running and enabled at boot'
      ansible.builtin.systemd:
        name: jira
        state: started
        enabled: true
      when: not ansible_check_mode
