---

- name: 'Create Jira unit for SystemD'
  ansible.builtin.template:
    src: jira.service.j2
    dest: /etc/systemd/system/jira.service
    owner: '{{ jira__username }}'
    group: '{{ jira__group }}'
    mode: 0644
  notify: Restart Jira

- name: 'Configure Jira'
  ansible.builtin.template:
    src: 'server.xml.j2'
    dest: '{{ jira__install_path }}/conf/server.xml'
    owner: '{{ jira__username }}'
    group: '{{ jira__group }}'
    mode: 0644
  notify: Restart Jira

- name: 'Configure Jira environment'
  ansible.builtin.template:
    src: 'setenv.sh.j2'
    dest: '{{ jira__install_path }}/bin/setenv.sh'
    owner: '{{ jira__username }}'
    group: '{{ jira__group }}'
    mode: 0755
  notify: Restart Jira
