---
- name: 'Configure Jira database connection'
  ansible.builtin.template:
    src: 'dbconfig.xml.j2'
    dest: '{{ jira_home_path }}/dbconfig.xml'
    owner: '{{ jira_username }}'
    group: '{{ jira_group }}'
    mode: 0600
  notify: Restart Jira
  become: true
