---
- name: 'Check the current Jira version'
  ansible.builtin.command:
    cmd: grep -Po '(?<=^version=)\N*$' '{{ _jira_application_path }}/atlassian-jira/META-INF/maven/com.atlassian.jira/jira-webapp-dist/pom.properties'
  failed_when: false
  changed_when: false
  register: __jira_version_check

- name: 'Download and unarchive Jira'
  when:
    - not ansible_check_mode
    - __jira_version_check.stdout is not defined or
      jira_version not in __jira_version_check.stdout
  block:
    - name: 'Download the Jira archive to a local folder'
      ansible.builtin.get_url:
        url: '{{ jira_download_url }}/{{ jira_archive_name }}'
        dest: '/tmp/{{ jira_archive_name }}'
        mode: 0644
      delegate_to: localhost

    - name: 'Unarchive Jira'
      ansible.builtin.unarchive:
        src: '/tmp/{{ jira_archive_name }}'
        dest: '{{ _jira_install_path }}'
        owner: '{{ jira_user }}'
        group: '{{ jira_group }}'
        extra_opts:
          - '--strip-components=1'
      become: true

- name: 'Create the symbolic link to Jira installation path'
  ansible.builtin.file:
    src: '{{ _jira_install_path }}'
    dest: '{{ _jira_application_path }}'
    state: 'link'
  when: not ansible_check_mode
  become: true
