---

- name: 'Install fontconfig'
  ansible.builtin.package:
    name: fontconfig
    state: present

- name: 'Create Jira group'
  ansible.builtin.group:
    name: '{{ jira__group }}'

- name: 'Create Jira user'
  ansible.builtin.user:
    name: '{{ jira__username }}'
    group: '{{ jira__group }}'
    comment: 'Atlassian JIRA'
    shell: /bin/bash
  register: jira__user_result

- name: 'Create Jira directories'
  ansible.builtin.file:
    path: '{{ item }}'
    owner: '{{ jira__username }}'
    group: '{{ jira__group }}'
    state: directory
    mode: 0755
  with_items:
    - '{{ jira__install_path }}'
    - '{{ jira__home_path }}'
