---
- name: 'Prepare for installing Jira'
  become: true
  block:
    - name: 'Update the APT package cache'
      ansible.builtin.apt:
        update_cache: true
      check_mode: false
      when: ansible_os_family == 'Debian'

    - name: 'Ensure the dependencies are installed'
      ansible.builtin.package:
        name:
          - 'fontconfig'
          - 'tar'
        state: 'present'

    - name: 'Create a Jira group'
      ansible.builtin.group:
        name: '{{ jira_group }}'

    - name: 'Create a Jira user'
      ansible.builtin.user:
        name: '{{ jira_user }}'
        group: '{{ jira_group }}'
        comment: 'Atlassian JIRA'
        shell: '/bin/bash'

    - name: 'Create Jira directories'
      ansible.builtin.file:
        path: '{{ jira_path }}'
        owner: '{{ jira_user }}'
        group: '{{ jira_group }}'
        state: 'directory'
        mode: 0755
      loop:
        - '{{ jira_install_path }}/{{ jira_version }}'
        - '{{ jira_home_path }}'
      loop_control:
        loop_var: jira_path
