---
- name: 'Install fontconfig'
  ansible.builtin.package:
    name: fontconfig
    state: present

- name: 'Create Jira group'
  ansible.builtin.group:
    name: '{{ jira_group }}'

- name: 'Create Jira user'
  ansible.builtin.user:
    name: '{{ jira_username }}'
    group: '{{ jira_group }}'
    comment: 'Atlassian JIRA'
    shell: /bin/bash
  register: _jira_user_result

- name: 'Create Jira directories'
  ansible.builtin.file:
    path: '{{ item }}'
    owner: '{{ jira_username }}'
    group: '{{ jira_group }}'
    state: directory
    mode: 0755
  with_items:
    - '{{ _jira_install_path }}'
    - '{{ jira_home_path }}'
