---
- name: 'Prepare for installing Jira'
  become: true
  block:
    - name: 'Debian | Install fontconfig'
      ansible.builtin.apt:
        name: 'fontconfig'
        update_cache: true
        state: 'present'
      when:
        - not ansible_check_mode
        - ansible_os_family == 'Debian'

    - name: 'RedHat | Install fontconfig'
      ansible.builtin.package:
        name: 'fontconfig'
        state: 'present'
      when: ansible_os_family == 'RedHat'

    - name: 'Create a Jira group'
      ansible.builtin.group:
        name: '{{ jira_group }}'

    - name: 'Create a Jira user'
      ansible.builtin.user:
        name: '{{ jira_user }}'
        group: '{{ jira_group }}'
        comment: 'Atlassian JIRA'
        shell: '/bin/bash'

    - name: 'Create Jira directories'
      ansible.builtin.file:
        path: '{{ jira_path }}'
        owner: '{{ jira_user }}'
        group: '{{ jira_group }}'
        state: 'directory'
        mode: 0755
      loop:
        - '{{ _jira_install_path }}'
        - '{{ jira_home_path }}'
      loop_control:
        loop_var: jira_path
