---
- name: Converge
  hosts: all

  pre_tasks:
    - name: 'Update apt cache'
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

    - name: 'Install tzdata-java package'
      ansible.builtin.package:
        name: 'tzdata-java'
      when: ansible_os_family == 'RedHat'

  roles:
    - role: geerlingguy.java
    - role: antmelekhin.jira
