---
- name: 'Verify'
  hosts: all
  gather_facts: false
  tasks:
    - name: 'Gathering Service Facts'
      ansible.builtin.service_facts:

    - name: 'Assert that jira service is enabled and running'
      ansible.builtin.assert:
        that:
          - ansible_facts.services['jira.service'].state == 'running'
          - ansible_facts.services['jira.service'].status == 'enabled'

    - name: 'Check url'
      ansible.builtin.uri:
        url: 'http://{{ ansible_host }}:8080'

    - name: 'Check current Jira version'
      ansible.builtin.command:
        cmd: grep -Po '(?<=^version=)\N*$' /opt/atlassian/jira/current/atlassian-jira/META-INF/maven/com.atlassian.jira/jira-webapp-dist/pom.properties
      changed_when: false
      register: _jira_version_check

    - name: 'Version output'
      ansible.builtin.debug:
        var: _jira_version_check.stdout
