---
# This is an example playbook to execute Ansible tests.

- name: 'Verify'
  hosts: all
  gather_facts: false
  tasks:

  - name: 'Gathering Service Facts'
    service_facts:

  - name: 'Assert that jira service is enabled and running'
    assert:
      that:
        - ansible_facts.services['jira.service'].state == 'running'
        - ansible_facts.services['jira.service'].status == 'enabled'

  - name: 'Check url'
    uri:
      url: 'http://{{ ansible_host }}:8080'

  - name: 'Check version'
    command: grep ^version /opt/atlassian/jira/atlassian-jira/META-INF/maven/com.atlassian.jira/jira-webapp-dist/pom.properties
    register: jira__version

  - name: 'Debug version'
    debug:
      var: jira__version.stdout_lines
